#!/bin/bash -e

# Eliminar la carpeta "externos" dentro de la carpeta distribuidora
cd distribuidora 
cd externos 
cd pendientes
rm lista.txt
rm lista.txt
cd ..
rmdir pendientes
cd distribuidora 
rmdir externos
