#!/bin/bash -e

# Eliminar la carpeta "externos" dentro de la carpeta distribuidora 
cd externos 
cd pendientes 
rm lista.txt
cd ..
rmdir pendientes 
cd ..
cd ..
cd externos 
rm lista.txt
cd distribuidora
rmdir externos


