#!/bin/bash -e

# Eliminar la carpeta "externos" dentro de la carpeta distribuidora 
cd externos 
rm lista.txt
cd ..
cd pendientes 
rm lista.txt
cd ..
cd externos 
rmdir pendientes 
cd ..
cd distribuidora 
rmdir externos 


